export default [
    { id: 1, endpoint: "notfound" },
    { id: 2, endpoint: "racingcars" },
    { id: 3, endpoint: "running" },
    { id: 4, endpoint: "cycling" },
    { id: 5, endpoint: "swimming" },
    { id: 6, endpoint: "triathlon" },
    { id: 7, endpoint: "hiking" },
    { id: 8, endpoint: "walking" },
    { id: 9, endpoint: "skating" },
    { id: 10, endpoint: "skiing" },
    { id: 11, endpoint: "snowboarding" },
    { id: 12, endpoint: "climbing" },
    { id: 13, endpoint: "adventure_racing" },
    { id: 14, endpoint: "obstacle_racing" },
];